### ISSUE TITLE
Update to later keycloak version ~v26

### ISSUE THREAD

**Issue by TrueType** [b13/ddev-keycloak#4]
Hi,

currently the v23 ist used with deprecated --proxy edge starting parameter.
https://github.com/b13/ddev-keycloak/blob/2d7af9c9aae4579c3e45a59b9ed5fd0622b82a86/docker-compose.keycloak.yaml#L6
https://github.com/b13/ddev-keycloak/blob/2d7af9c9aae4579c3e45a59b9ed5fd0622b82a86/docker-compose.keycloak.yaml#L7

Do you have a later v26 configuration on and running? Please share.

**Comment by fchaussin** [comment]
Hi! You can easily update on v25 but the export will not work, I can give you my docker-compose on monday if you can wait. Have a nice weekend

**Comment by TrueType** [comment]
This may help - https://www.keycloak.org/docs/24.0.5/upgrading/index.html
I could get it running with
```
image: quay.io/keycloak/keycloak:26.0.5
command: start-dev --proxy-headers xforwarded --import-realm
```
My version is pinned on 26.0.5. The `--proxy edge` breaks already with v24.

**Comment by TrueType** [comment]
You, too, have a nice weekend. I use the Keycloak for development. With the upgrades to later images the full setup stayed unchanged (realms, users,..). That was real nice.

**Comment by weitzman** [comment]
Keycloak keeps adding great new features. I agree that it would be nice to use them with this add-on.

**Comment by fchaussin** [comment]
My current `.ddev/docker-compose.keycloak.yaml` looks like this :

```yaml
services:
  keycloak_db:
    container_name: ddev-${DDEV_SITENAME}-keycloak-db
    image: postgres:14
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak

  keycloak:
    container_name: ddev-${DDEV_SITENAME}-keycloak
    hostname: keycloak.${DDEV_SITENAME}.ddev.site
    image: quay.io/keycloak/keycloak:26.3.2
    command: start-dev --import-realm
    depends_on:
      - keycloak_db
    labels:
      com.ddev.site-name: keycloak.${DDEV_SITENAME}.ddev.site
      com.ddev.approot: $DDEV_APPROOT
    environment:
      - VIRTUAL_HOST=keycloak.${DDEV_SITENAME}.ddev.site
      - HTTP_EXPOSE=8442:8080
      - HTTPS_EXPOSE=8443:8080
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KC_HOSTNAME=https://keycloak.${DDEV_SITENAME}.ddev.site:8443
      # PostgreSQL connection settings
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak_db:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak

    volumes:
      - keycloak:/opt/keycloak/data/
      - .:/mnt/ddev_config
      - ./keycloak/themes:/opt/keycloak/themes/
  web:
    links:
      - keycloak

volumes:
  keycloak:
  keycloak-db-data:
```

It works fine in the local environment. I’ve upgraded incrementally to this version to keep the config file up to date, running `ddev kcctl export` after each step (23.0 → 23.1 → 23.2 → … → 26.2 → 26.3). Sometimes the config file isn’t fully compatible with the new version and the CLI command fails; in such cases, a partial export/import between versions via the GUI can help.
